### ISSUE TITLE
epoll_pwait2 exists but is unsupported

### ISSUE THREAD

**Issue by joshheinrichs-shopify** [socketry/io-event#57]
when using io/event v1.2.0 in ubuntu jammy containers running on kernel 5.10, we encounter this error:

```
.../gems/async-2.5.0/lib/async/scheduler.rb:221:in `select': Function not implemented - select_internal_with_gvl:epoll_wait 
```

this appears to be due to epoll_pwait2 returning ENOSYS, similar to the issue described here https://github.com/netty/netty/pull/12345

**Comment by ioquatix** [comment]
What would be the best way to deal with this?

- More elaborate build time check?
- More elaborate run time check?
- Environment/configuration variable to disable.

**Comment by joshheinrichs-shopify** [comment]
a runtime check falling back to the old method if `epoll_pwait2` is unsupported might be ideal since an image could feasibly get built on a newer kernel than it ends up running on. in my case i upgraded the kernel so this issue isn't affecting me anymore.

**Comment by morgoth** [comment]
Got the same issue after upgrading io-event to 1.2.0 via async gem.
`Errno::ENOSYS: Function not implemented - select_internal_with_gvl:epoll_wait`

We're using heroku deployment, so it's their ruby buildpack (ruby 3.2.2) used internally

**Comment by ioquatix** [comment]
The simplest solution is just to pin to `io-event` 1.1.x - I'm not sure a runtime check is a good idea just because of the additional complexity it adds. But I suppose it's the most reliable. Does that mean that the Heroku build environment is running a different kernel to the deployment environment?

**Comment by morgoth** [comment]
I froze the gem, yes.

I really don't know how exactly the deploy process is happening.
https://github.com/heroku/heroku-buildpack-ruby

@schneems are you still maintaining heroku Ruby buildpack? Could you give us some insights?

**Comment by trevorturk** [comment]
> The simplest solution is just to pin to `io-event` 1.1.x - I'm not sure a runtime check is a good idea just because of the additional complexity it adds. But I suppose it's the most reliable. Does that mean that the Heroku build environment is running a different kernel to the deployment environment?

I noticed this issue and pinned `io-event` to `~> 1.1.0` to avoid issues, but I did a bit of testing, just to see how things behaved on Heroku for me. The deployment went through fine (no errors during `bundle install` but then the app failed to boot with the error described. 

I wonder if there would be an option to check at build time (during `bundle install`) if a runtime check is too complex? I'm not clear on if the build environment is different to the deployment environment. I'm happy to open a support issue with Heroku if that would be beneficial, perhaps we could get some additional information. 

Thanks for your attention -- I just wanted to bring a bit more information here, and to note that this is a bit of a scary issue on Heroku since you can deploy seemingly just fine, but then the app fails to boot, which could result in surprising downtime for unsuspecting `io-event` users!

**Comment by ioquatix** [comment]
It does appear this problem is manifesting, at least on Heroku, because the build and runtime kernels are different. If you could confirm that, it would be helpful.

It does look like a runtime check will be useful in practice.

**Comment by trevorturk** [comment]
Just a note to say that I submitted a ticket with Heroku support in the hopes of getting a bit more information here. I'll report back if/when I hear anything back!

**Comment by schneems** [comment]
> We're using heroku deployment, so it's their ruby buildpack (ruby 3.2.2) used internally

The issue, as I understand, is with the operating system (i.e. ubuntu) and not with the way Ruby was compiled or how the Ruby buildpack configures it. 

> Does that mean that the Heroku build environment is running a different kernel to the deployment environment?

Sometimes yes. Here's a full list of all packages https://devcenter.heroku.com/articles/stack-packages. Some packages are build time only.

> (no errors during bundle install but then the app failed to boot with the error described.

@ioquatix  Is one of the libraries that are build time only needed by io-event? https://devcenter.heroku.com/articles/stack-packages. 

Also, I'm curious about the timing here. It looks like io-event was released [1.2.0](https://rubygems.org/gems/io-event/versions/1.2.0) - April 30, 2023. Has it been broken since then or was it working and then stopped working?

**Comment by trevorturk** [comment]
I'll try to answer a couple questions...

> The issue, as I understand, is with the operating system (i.e. ubuntu) and not with the way Ruby was compiled or how the Ruby buildpack configures it.

Yes, I think the build env has the `epoll_pwait2` function, but the deployment env does not. 

> @ioquatix Is one of the libraries that are build time only needed by io-event? https://devcenter.heroku.com/articles/stack-packages.

I suspect finding the answer to this question will lead to the solution/explanation. 

> Also, I'm curious about the timing here. It looks like io-event was released [1.2.0](https://rubygems.org/gems/io-event/versions/1.2.0) - April 30, 2023. Has it been broken since then or was it working and then stopped working?

I believe this is was breaking change: https://github.com/socketry/io-event/commit/d665fd341394cec578057594bbf33628d5f9bb65

**Comment by ioquatix** [comment]
It's also possible that the header file exposes `epoll_pwait2` without it actually being implemented by the kernel which would explain the `ENOSYS`. We probably need to detect if it's actually working.

**Comment by ioquatix** [comment]
Released updated `io-event` v1.2.1.

**Comment by schneems** [comment]
>  a new requirement in io-event, which Heroku's build env supports, but the deployment env does not.

I would like some more info here. If we know which of those packages is in build but not dev, I can do the work to see what's needed to get it into dev. 

> It's also possible that the header file exposes epoll_pwait2 without it actually being implemented by the kernel which would explain the ENOSYS.

That would be a canonical issue (I think). If it's not in an issue due to the packages we might be able to follow up with canonical.

**Comment by trevorturk** [comment]
I'm a bit out of my depth here, but just to note that I tested `io-event` v1.2.1 on my Heroku app (`helloweather-staging`, in case it would be helpful to see, @schneems) and the build env and deployment env seem happy now. 

Reading https://github.com/socketry/io-event/pull/59 it sounds like @ioquatix suspects this might be a kernel issue (a Canonical Ubuntu issue, as opposed to a package issue?) where I wonder if the kernel used in the Heroku build env might be different than the one used in the deployment env? Is that something you could confirm, @schneems? Otherwise, if we're using the same kernel, I guess it must be a difference in the packages, and we can try to figure out which one. 

FWIW I searched a bit and found this: https://manpages.ubuntu.com/cgi-bin/search.py?q=epoll_pwait2 which indicates that `KINETIC 22.10` has support, but perhaps there are patch versions where an older version indicates support but doesn't actually have support or something like that?

**Comment by schneems** [comment]
>  where I wonder if the kernel used in the Heroku build env might be different than the one used in the deployment env?

It is not. Packages differ, but not the base OS. I think it's more likely something like Samuel is saying is happening where the header exists so it compiles fine, but when you go to actually use it, the call fails. 

> which indicates that KINETIC 22.10 has support,

We only use the LTS Ubuntu versions so heroku-22 is based on 22.04. I'm not a Linux guru by any means but I know some. I can ask to poke around a bit.

**Comment by trevorturk** [comment]
Gotcha, maybe Samuel can help point us in the right direction. Thank you for the help, it's very much appreciated!

**Comment by ioquatix** [comment]
> happening where the header exists so it compiles fine, but when you go to actually use it, the call fails.

I think this is it.

**Comment by schneems** [comment]
To loop back here. I want to share some extra information that I've learned: It looks like this interface comes from the kernel, not a package. An OS is not locked to a specific kernel. One OS can run on multiple different kernels. Heroku runs builds (and runtime) on containers. Containers inherit the kernel of the host right now our host does not have epoll_pwait2.

Long term on the Heroku front we need to move to a kernel that includes `epoll_pwait2` . Authors who want to use features like this need to check that the feature is available in the kernel in addition to making sure that the header exists. It looks like that's been handled by #59.

**Comment by trevorturk** [comment]
That's great, thank you for digging into that a bit further. 

I'm happily using the workaround from https://github.com/socketry/io-event/pull/59 for now. 

Please let me know if there's any advantage to filing an issue on the Heroku public roadmap or anything like that, but I don't think it's a big deal now that we have the workaround in place.

**Comment by schneems** [comment]
> Please let me know if there's any advantage to filing an issue on the Heroku public roadmap 

That's a great idea actually. It's pretty low level and in-the-weeds but I think that's a good place to raise that issue. (Or if it's not then we'll both get that feedback at the same time). You can link back to this thread.

In a related discussion I think io_uring is also not available (though I could be mis-remembering). Both this epoll_pwait2 and io_uring are coming from the kernel (IIRC) so they could be captured in a "please upgrade the kernel" product roadmap request.
